name: Deploy to Contabo VM

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../backend && npm ci

    - name: Build frontend
      run: |
        cd frontend
        echo "VITE_API_URL=https://lab.cipme.ci/api" > .env
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /opt/growf

          # Pull latest changes
          git pull origin master

          # Install backend dependencies
          cd backend
          sudo -u growf npm install
          sudo -u growf npx prisma generate

          # Build frontend with production config
          cd ../frontend
          echo "VITE_API_URL=https://lab.cipme.ci/api" > .env
          sudo -u growf npm install
          sudo -u growf npx vite build

          # Restart PM2
          sudo -u growf pm2 restart growf-backend || sudo -u growf pm2 start ecosystem.config.js

          # Reload Nginx
          systemctl reload nginx

          # Check status
          sleep 5
          sudo -u growf pm2 status
          curl -f http://localhost:3005/health || echo "Backend health check failed"